// await page.goto('https://demo.inventree.org/web/login');
// await page.getByRole('textbox', { name: 'login-username' }).click();
// await page.getByRole('textbox', { name: 'login-username' }).fill('allaccess');
// await page.getByRole('textbox', { name: 'login-password' }).click();
// await page.getByRole('textbox', { name: 'login-password' }).fill('nolimits');
// await page.getByRole('button', { name: 'Log In' }).click();
// await page.goto('https://demo.inventree.org/web/home');
// await expect(page.locator('#root')).toContainText('InvenTree Demo Server - Ally Access');
// await expect(page.getByRole('link', { name: 'Parts' })).toBeVisible();
// await page.getByRole('link', { name: 'Parts' }).click();
// await expect(page.locator('#root')).toContainText('Parts');
// await expect(page.getByLabel('panel-tabs-partcategory').getByRole('link', { name: 'Parts' })).toBeVisible();
// await page.getByLabel('panel-tabs-partcategory').getByRole('link', { name: 'Parts' }).click();
// await expect(page.locator('thead')).toContainText('Part');
// await expect(page.locator('thead')).toContainText('IPN');
// await expect(page.locator('thead')).toContainText('Revision');
// await expect(page.locator('thead')).toContainText('Units');
// await expect(page.locator('thead')).toContainText('Description');
// await expect(page.locator('thead')).toContainText('Category');
// await page.getByRole('button', { name: 'action-menu-add-parts' }).click();
// await page.getByRole('menuitem', { name: 'action-menu-add-parts-create-' }).click();
// await page.locator('.css-8mmkcg').first().click();
// await page.getByText('ElectronicsElectronic').click();
// await page.getByRole('textbox', { name: 'text-field-name' }).click();
// await page.getByRole('textbox', { name: 'text-field-name' }).fill('Test Electronics');
// await page.getByRole('textbox', { name: 'text-field-IPN' }).click();
// await page.getByRole('textbox', { name: 'text-field-IPN' }).fill('IPN-12345');
// await page.getByRole('textbox', { name: 'text-field-description' }).click();
// await page.getByRole('textbox', { name: 'text-field-description' }).fill('IPN Description');
// await page.getByRole('textbox', { name: 'text-field-revision' }).click();
// await page.getByRole('textbox', { name: 'text-field-revision' }).fill('Rev12345');
// await page.locator('#mantine-c7l3cfpv5 > .css-4yylii-control > .css-1wy0on6 > .css-23xn0o-indicatorContainer > .css-8mmkcg').click();
// await page.locator('#react-select-3-option-1').getByText('1551ABK').click();
// await page.locator('#mantine-jmkfayodt > .css-4yylii-control > .css-1wy0on6 > .css-23xn0o-indicatorContainer > .css-8mmkcg > path').click();
// await page.locator('#mantine-jmkfayodt > .css-4yylii-control > .css-1wy0on6 > .css-23xn0o-indicatorContainer > .css-8mmkcg').click();
// await page.getByText('widget.blue | Blue Widget').click();
// await page.getByRole('textbox', { name: 'text-field-units' }).click();
// await page.getByRole('textbox', { name: 'text-field-units' }).fill('120');
// await page.locator('#mantine-ld17xe4lq > .css-4yylii-control > .css-1wy0on6 > .css-23xn0o-indicatorContainer > .css-8mmkcg > path').click();
// await page.locator('#mantine-ld17xe4lq > .css-4yylii-control > .css-hlgwow > .css-z6y6gf').click();
// await page.getByTitle('adams truck').click();
// await page.getByRole('textbox', { name: 'number-field-initial_stock.' }).click();
// await page.getByRole('textbox', { name: 'number-field-initial_stock.' }).fill('150');
// await page.getByRole('button', { name: 'Submit' }).click();
// await page.locator('.css-4yylii-control > .css-1wy0on6 > .css-1od0356-indicatorContainer > .css-8mmkcg > path').first().click();
// await page.locator('.css-1cbzoft-indicatorContainer > .css-8mmkcg > path').click();
// await page.getByRole('button', { name: 'Submit' }).click();
// await page.goto('https://demo.inventree.org/web/part/1114/details');
// await expect(page.locator('#root')).toContainText('In Stock: 150');
// await expect(page.getByLabel('Part Details')).toContainText('Test Electronics');
// await expect(page.getByLabel('Part Details')).toContainText('Electronics');
// await expect(page.getByLabel('Part Details')).toContainText('120');
// await expect(page.locator('#mantine-ju0pgaoa0-target')).toContainText('allaccess');

await page.getByRole('button', { name: 'action-menu-add-parts' }).click();
await page.getByRole('menuitem', { name: 'action-menu-add-parts-import-' }).click();
await page.getByRole('button', { name: 'file-field-data_file' }).click();
await page.getByRole('button', { name: 'file-field-data_file' }).setInputFiles('Import_InvenTree_Part_import_file_template.csv');
await page.getByRole('button', { name: 'Submit' }).click();
await page.getByRole('button', { name: 'Accept Column Mapping' }).click();


